# Generated by Django 3.2.18 on 2023-02-17 01:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'holidays',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='position name')),
            ],
            options={
                'db_table': 'positions',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('in_am', models.TimeField()),
                ('out_am', models.TimeField()),
                ('in_pm', models.TimeField()),
                ('out_pm', models.TimeField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='Signatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signatory', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'signatory',
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'threshold',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=14, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(13, message='ID must be at least 13 characters.')])),
                ('firstname', models.CharField(max_length=40, verbose_name='* Firstname')),
                ('middlename', models.CharField(max_length=40, verbose_name='* Middlename')),
                ('lastname', models.CharField(max_length=40, verbose_name='* Lastname')),
                ('suffix', models.CharField(blank=True, max_length=40, null=True)),
                ('birth_date', models.DateField(verbose_name='* Birthdate')),
                ('mobile_number', models.CharField(blank=True, max_length=11, null=True)),
                ('barangay', models.CharField(max_length=30, verbose_name='* Barangay')),
                ('municipality', models.CharField(max_length=30, verbose_name='* Municipality')),
                ('province', models.CharField(max_length=30, verbose_name='* Province')),
                ('id_picture', models.ImageField(upload_to='', verbose_name='Picture ID')),
                ('date_employed', models.DateField(blank=True, null=True)),
                ('license_no', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('position', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='employees.position', verbose_name='* Position')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=30)),
                ('in_am', models.TimeField(blank=True, null=True)),
                ('out_am', models.TimeField(blank=True, null=True)),
                ('in_pm', models.TimeField(blank=True, null=True)),
                ('out_pm', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1, null=True)),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
