# Generated by Django 4.1.5 on 2023-01-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_picture',
            field=models.ImageField(upload_to='', verbose_name='Picture ID'),
        ),
    ]
