# Generated by Django 4.1.4 on 2023-01-20 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_position_rename_biometric_id_employee_id_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='licensed_no',
            new_name='license_no',
        ),
    ]
