# Generated by Django 4.1.5 on 2023-01-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_id_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'threshold',
            },
        ),
    ]
