# Generated by Django 4.1.4 on 2023-01-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employment_status',
        ),
    ]
