# Generated by Django 4.1.4 on 2022-12-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
