# Generated by Django 4.1.4 on 2023-01-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='designation name'),
        ),
    ]
