# Generated by Django 4.1.4 on 2022-12-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_designation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
