# Generated by Django 4.1.4 on 2022-12-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_schedule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
