# Generated by Django 3.2.16 on 2023-01-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_signatory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signatory',
            table='signatory',
        ),
    ]
