# Generated by Django 4.1.4 on 2023-01-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Barangay',
            new_name='barangay',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Municipality',
            new_name='municipality',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Province',
            new_name='province',
        ),
    ]
