# Generated by Django 4.1.5 on 2023-01-10 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_department_name_alter_designation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(13, message='ID must be at least 13 characters.')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middlename',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
