# Generated by Django 3.2.16 on 2023-01-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_signatory_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signatory',
            name='signatory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
