# Generated by Django 4.1.4 on 2023-01-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_rename_barangay_employee_barangay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='reportsTo',
        ),
    ]
