# Generated by Django 3.2.16 on 2023-01-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_signatory_signatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='signatory',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
