# Generated by Django 4.1.4 on 2022-12-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_holiday'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='holiday',
            table='holidays',
        ),
    ]
