# Generated by Django 3.2.16 on 2023-02-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_signatory_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='suffix',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(max_length=40, verbose_name='* Firstname'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastname',
            field=models.CharField(max_length=40, verbose_name='* Lastname'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middlename',
            field=models.CharField(max_length=40, verbose_name='* Middlename'),
        ),
    ]
