# Generated by Django 3.2.16 on 2023-02-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_auto_20230202_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
