# Generated by Django 4.1.4 on 2022-12-26 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employee_reportsto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employee'),
        ),
    ]
