# Generated by Django 4.1.4 on 2022-12-27 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_alter_attendance_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='ref_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
    ]
