# Generated by Django 4.1.4 on 2022-12-27 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_attendance_ref_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='ref_id',
            new_name='reference',
        ),
    ]
