# Generated by Django 4.1.4 on 2022-12-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_rename_ref_id_attendance_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='remarks',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
